{
  "platform": {
    "name": "Heimdall Tools",
    "release": "2.10.15",
    "target_id": null
  },
  "version": "2.10.15",
  "statistics": {
    "duration": null
  },
  "profiles": [
    {
      "name": "Anchore - Grype",
      "title": "Anchore Grype Matches",
      "version": "0.79.3",
      "maintainer": null,
      "summary": null,
      "license": null,
      "copyright": null,
      "copyright_email": null,
      "supports": [],
      "attributes": [],
      "depends": [],
      "groups": [],
      "status": "loaded",
      "controls": [
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "ALAS-2024-2607",
            "severity": "Low"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 2023.2.68-1.amzn2.0.1",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://alas.aws.amazon.com/AL2/ALAS-2024-2607.html"
            },
            {
              "url": "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"
            },
            {
              "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"
            },
            {
              "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to ALAS-2024-2607 in cloudwatch_to_s3:latest",
          "id": "Grype/ALAS-2024-2607",
          "desc": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.05.30 and prior to 2024.07.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.07.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\" (CVE-2024-39689)",
          "impact": 0.3,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"ALAS-2024-2607\",\n    \"dataSource\": \"https://alas.aws.amazon.com/AL2/ALAS-2024-2607.html\",\n    \"namespace\": \"amazon:distro:amazonlinux:2\",\n    \"severity\": \"Low\",\n    \"urls\": [\n      \"https://alas.aws.amazon.com/AL2/ALAS-2024-2607.html\"\n    ],\n    \"description\": \"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.05.30 and prior to 2024.07.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.07.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \\\"long-running and unresolved compliance issues.\\\" (CVE-2024-39689)\",\n    \"cvss\": [],\n    \"fix\": {\n      \"versions\": [\n        \"2023.2.68-1.amzn2.0.1\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2024-39689\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-39689\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"High\",\n      \"urls\": [\n        \"https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463\",\n        \"https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc\",\n        \"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI\"\n      ],\n      \"description\": \"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.05.30 and prior to 2024.07.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.07.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \\\"long-running and unresolved compliance issues.\\\"\",\n      \"cvss\": [\n        {\n          \"source\": \"security-advisories@github.com\",\n          \"type\": \"Secondary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N\",\n          \"metrics\": {\n            \"baseScore\": 7.5,\n            \"exploitabilityScore\": 3.9,\n            \"impactScore\": 3.6\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"rpm-matcher\",\n    \"searchedBy\": {\n      \"distro\": {\n        \"type\": \"amazonlinux\",\n        \"version\": \"2\"\n      },\n      \"namespace\": \"amazon:distro:amazonlinux:2\",\n      \"package\": {\n        \"name\": \"ca-certificates\",\n        \"version\": \"0:2023.2.64-1.amzn2.0.1\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"< 2023.2.68-1.amzn2.0.1 (rpm)\",\n      \"vulnerabilityID\": \"ALAS-2024-2607\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"3fdee4f2791be89b\",\n  \"name\": \"ca-certificates\",\n  \"version\": \"2023.2.64-1.amzn2.0.1\",\n  \"type\": \"rpm\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lib/rpm/Packages\",\n      \"layerID\": \"sha256:0044b36762beca646f20eb6730e3575ec671a8857b39485f38ba0e715d375483\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [\n    \"Public Domain\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:ca-certificates:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:ca-certificates:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:ca_certificates:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:ca_certificates:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:amazonlinux:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:amazonlinux:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:ca:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:ca:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:rpm/amzn/ca-certificates@2023.2.64-1.amzn2.0.1?arch=noarch&upstream=ca-certificates-2023.2.64-1.amzn2.0.1.src.rpm&distro=amzn-2\",\n  \"upstreams\": [],\n  \"metadataType\": \"RpmMetadata\",\n  \"metadata\": {\n    \"epoch\": null,\n    \"modularityLabel\": \"\"\n  }\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "ALAS-2024-2595",
            "severity": "Medium"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 1.15.1-55.amzn2.2.8",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://alas.aws.amazon.com/AL2/ALAS-2024-2595.html"
            },
            {
              "url": "https://github.com/krb5/krb5/commit/55fbf435edbe2e92dd8101669b1ce7144bc96fef"
            },
            {
              "url": "https://web.mit.edu/kerberos/www/advisories/"
            },
            {
              "url": "https://github.com/krb5/krb5/commit/55fbf435edbe2e92dd8101669b1ce7144bc96fef"
            },
            {
              "url": "https://web.mit.edu/kerberos/www/advisories/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to ALAS-2024-2595 in cloudwatch_to_s3:latest",
          "id": "Grype/ALAS-2024-2595",
          "desc": "krb5: GSS message token handling (CVE-2024-37370)In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can cause invalid memory reads during GSS message token handling by sending message tokens with invalid length fields. (CVE-2024-37371)",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"ALAS-2024-2595\",\n    \"dataSource\": \"https://alas.aws.amazon.com/AL2/ALAS-2024-2595.html\",\n    \"namespace\": \"amazon:distro:amazonlinux:2\",\n    \"severity\": \"Medium\",\n    \"urls\": [\n      \"https://alas.aws.amazon.com/AL2/ALAS-2024-2595.html\"\n    ],\n    \"description\": \"krb5: GSS message token handling (CVE-2024-37370)In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can cause invalid memory reads during GSS message token handling by sending message tokens with invalid length fields. (CVE-2024-37371)\",\n    \"cvss\": [],\n    \"fix\": {\n      \"versions\": [\n        \"1.15.1-55.amzn2.2.8\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2024-37370\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-37370\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"High\",\n      \"urls\": [\n        \"https://github.com/krb5/krb5/commit/55fbf435edbe2e92dd8101669b1ce7144bc96fef\",\n        \"https://web.mit.edu/kerberos/www/advisories/\"\n      ],\n      \"description\": \"In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can modify the plaintext Extra Count field of a confidential GSS krb5 wrap token, causing the unwrapped token to appear truncated to the application.\",\n      \"cvss\": [\n        {\n          \"source\": \"nvd@nist.gov\",\n          \"type\": \"Primary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N\",\n          \"metrics\": {\n            \"baseScore\": 7.5,\n            \"exploitabilityScore\": 3.9,\n            \"impactScore\": 3.6\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    },\n    {\n      \"id\": \"CVE-2024-37371\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-37371\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"Critical\",\n      \"urls\": [\n        \"https://github.com/krb5/krb5/commit/55fbf435edbe2e92dd8101669b1ce7144bc96fef\",\n        \"https://web.mit.edu/kerberos/www/advisories/\"\n      ],\n      \"description\": \"In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can cause invalid memory reads during GSS message token handling by sending message tokens with invalid length fields.\",\n      \"cvss\": [\n        {\n          \"source\": \"nvd@nist.gov\",\n          \"type\": \"Primary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H\",\n          \"metrics\": {\n            \"baseScore\": 9.1,\n            \"exploitabilityScore\": 3.9,\n            \"impactScore\": 5.2\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"rpm-matcher\",\n    \"searchedBy\": {\n      \"distro\": {\n        \"type\": \"amazonlinux\",\n        \"version\": \"2\"\n      },\n      \"namespace\": \"amazon:distro:amazonlinux:2\",\n      \"package\": {\n        \"name\": \"krb5-libs\",\n        \"version\": \"0:1.15.1-55.amzn2.2.7\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"< 1.15.1-55.amzn2.2.8 (rpm)\",\n      \"vulnerabilityID\": \"ALAS-2024-2595\"\n    }\n  },\n  {\n    \"type\": \"exact-indirect-match\",\n    \"matcher\": \"rpm-matcher\",\n    \"searchedBy\": {\n      \"distro\": {\n        \"type\": \"amazonlinux\",\n        \"version\": \"2\"\n      },\n      \"namespace\": \"amazon:distro:amazonlinux:2\",\n      \"package\": {\n        \"name\": \"krb5\",\n        \"version\": \"1.15.1-55.amzn2.2.7\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"< 1.15.1-55.amzn2.2.8 (rpm)\",\n      \"vulnerabilityID\": \"ALAS-2024-2595\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"3bb967025c5652e0\",\n  \"name\": \"krb5-libs\",\n  \"version\": \"1.15.1-55.amzn2.2.7\",\n  \"type\": \"rpm\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lib/rpm/Packages\",\n      \"layerID\": \"sha256:0044b36762beca646f20eb6730e3575ec671a8857b39485f38ba0e715d375483\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [\n    \"MIT\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:amazonlinux:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:amazonlinux:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:krb5-libs:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:krb5-libs:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:krb5_libs:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:krb5_libs:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:krb5:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:krb5:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:rpm/amzn/krb5-libs@1.15.1-55.amzn2.2.7?arch=aarch64&upstream=krb5-1.15.1-55.amzn2.2.7.src.rpm&distro=amzn-2\",\n  \"upstreams\": [\n    {\n      \"name\": \"krb5\",\n      \"version\": \"1.15.1-55.amzn2.2.7\"\n    }\n  ],\n  \"metadataType\": \"RpmMetadata\",\n  \"metadata\": {\n    \"epoch\": null,\n    \"modularityLabel\": \"\"\n  }\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "ALAS-2024-2604",
            "severity": "Medium"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 1.0.2k-24.amzn2.0.13",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://alas.aws.amazon.com/AL2/ALAS-2024-2604.html"
            },
            {
              "url": "http://www.openwall.com/lists/oss-security/2024/06/27/1"
            },
            {
              "url": "http://www.openwall.com/lists/oss-security/2024/06/28/4"
            },
            {
              "url": "https://github.com/openssl/openssl/commit/4ada436a1946cbb24db5ab4ca082b69c1bc10f37"
            },
            {
              "url": "https://github.com/openssl/openssl/commit/99fb785a5f85315b95288921a321a935ea29a51e"
            },
            {
              "url": "https://github.com/openssl/openssl/commit/cf6f91f6121f4db167405db2f0de410a456f260c"
            },
            {
              "url": "https://github.com/openssl/openssl/commit/e86ac436f0bd54d4517745483e2315650fae7b2c"
            },
            {
              "url": "https://github.openssl.org/openssl/extended-releases/commit/9947251413065a05189a63c9b7a6c1d4e224c21c"
            },
            {
              "url": "https://github.openssl.org/openssl/extended-releases/commit/b78ec0824da857223486660177d3b1f255c65d87"
            },
            {
              "url": "https://security.netapp.com/advisory/ntap-20240712-0005/"
            },
            {
              "url": "https://www.openssl.org/news/secadv/20240627.txt"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to ALAS-2024-2604 in cloudwatch_to_s3:latest",
          "id": "Grype/ALAS-2024-2604",
          "desc": "Issue summary: Calling the OpenSSL API function SSL_select_next_proto with anempty supported client protocols buffer may cause a crash or memory contents tobe sent to the peer.Impact summary: A buffer overread can have a range of potential consequencessuch as unexpected application beahviour or a crash. In particular this issuecould result in up to 255 bytes of arbitrary private data from memory being sentto the peer leading to a loss of confidentiality. However, only applicationsthat directly call the SSL_select_next_proto function with a 0 length list ofsupported client protocols are affected by this issue. This would normally neverbe a valid scenario and is typically not under attacker control but may occur byaccident in the case of a configuration or programming error in the callingapplication.The OpenSSL API function SSL_select_next_proto is typically used by TLSapplications that support ALPN (Application Layer Protocol Negotiation) or NPN(Next Protocol Negotiation). NPN is older, was never standardised andis deprecated in favour of ALPN. We believe that ALPN is significantly morewidely deployed than NPN. The SSL_select_next_proto function accepts a list ofprotocols from the server and a list of protocols from the client and returnsthe first protocol that appears in the server list that also appears in theclient list. In the case of no overlap between the two lists it returns thefirst item in the client list. In either case it will signal whether an overlapbetween the two lists was found. In the case where SSL_select_next_proto iscalled with a zero length client list it fails to notice this condition andreturns the memory immediately following the client list pointer (and reportsthat there was no overlap in the lists).This function is typically called from a server side application callback forALPN or a client side application callback for NPN. In the case of ALPN the listof protocols supplied by the client is guaranteed by libssl to never be zero inlength. The list of server protocols comes from the application and should nevernormally be expected to be of zero length. In this case if theSSL_select_next_proto function has been called as expected (with the listsupplied by the client passed in the client/client_len parameters), then theapplication will not be vulnerable to this issue. If the application hasaccidentally been configured with a zero length server list, and hasaccidentally passed that zero length server list in the client/client_lenparameters, and has additionally failed to correctly handle a \"no overlap\"response (which would normally result in a handshake failure in ALPN) then itwill be vulnerable to this problem.In the case of NPN, the protocol permits the client to opportunistically selecta protocol when there is no overlap. OpenSSL returns the first client protocolin the no overlap case in support of this. The list of client protocols comesfrom the application and should never normally be expected to be of zero length.However if the SSL_select_next_proto function is accidentally called with aclient_len of 0 then an invalid memory pointer will be returned instead. If theapplication uses this output as the opportunistic protocol then the loss ofconfidentiality will occur.This issue has been assessed as Low severity because applications are mostlikely to be vulnerable if they are using NPN instead of ALPN - but NPN is notwidely used. It also requires an application configuration or programming error.Finally, this issue would not typically be under attacker control making activeexploitation unlikely.The FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.Due to the low severity of this issue we are not issuing new releases ofOpenSSL at this time. The fix will be included in the next releases when theybecome available. (CVE-2024-5535)",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"ALAS-2024-2604\",\n    \"dataSource\": \"https://alas.aws.amazon.com/AL2/ALAS-2024-2604.html\",\n    \"namespace\": \"amazon:distro:amazonlinux:2\",\n    \"severity\": \"Medium\",\n    \"urls\": [\n      \"https://alas.aws.amazon.com/AL2/ALAS-2024-2604.html\"\n    ],\n    \"description\": \"Issue summary: Calling the OpenSSL API function SSL_select_next_proto with anempty supported client protocols buffer may cause a crash or memory contents tobe sent to the peer.Impact summary: A buffer overread can have a range of potential consequencessuch as unexpected application beahviour or a crash. In particular this issuecould result in up to 255 bytes of arbitrary private data from memory being sentto the peer leading to a loss of confidentiality. However, only applicationsthat directly call the SSL_select_next_proto function with a 0 length list ofsupported client protocols are affected by this issue. This would normally neverbe a valid scenario and is typically not under attacker control but may occur byaccident in the case of a configuration or programming error in the callingapplication.The OpenSSL API function SSL_select_next_proto is typically used by TLSapplications that support ALPN (Application Layer Protocol Negotiation) or NPN(Next Protocol Negotiation). NPN is older, was never standardised andis deprecated in favour of ALPN. We believe that ALPN is significantly morewidely deployed than NPN. The SSL_select_next_proto function accepts a list ofprotocols from the server and a list of protocols from the client and returnsthe first protocol that appears in the server list that also appears in theclient list. In the case of no overlap between the two lists it returns thefirst item in the client list. In either case it will signal whether an overlapbetween the two lists was found. In the case where SSL_select_next_proto iscalled with a zero length client list it fails to notice this condition andreturns the memory immediately following the client list pointer (and reportsthat there was no overlap in the lists).This function is typically called from a server side application callback forALPN or a client side application callback for NPN. In the case of ALPN the listof protocols supplied by the client is guaranteed by libssl to never be zero inlength. The list of server protocols comes from the application and should nevernormally be expected to be of zero length. In this case if theSSL_select_next_proto function has been called as expected (with the listsupplied by the client passed in the client/client_len parameters), then theapplication will not be vulnerable to this issue. If the application hasaccidentally been configured with a zero length server list, and hasaccidentally passed that zero length server list in the client/client_lenparameters, and has additionally failed to correctly handle a \\\"no overlap\\\"response (which would normally result in a handshake failure in ALPN) then itwill be vulnerable to this problem.In the case of NPN, the protocol permits the client to opportunistically selecta protocol when there is no overlap. OpenSSL returns the first client protocolin the no overlap case in support of this. The list of client protocols comesfrom the application and should never normally be expected to be of zero length.However if the SSL_select_next_proto function is accidentally called with aclient_len of 0 then an invalid memory pointer will be returned instead. If theapplication uses this output as the opportunistic protocol then the loss ofconfidentiality will occur.This issue has been assessed as Low severity because applications are mostlikely to be vulnerable if they are using NPN instead of ALPN - but NPN is notwidely used. It also requires an application configuration or programming error.Finally, this issue would not typically be under attacker control making activeexploitation unlikely.The FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.Due to the low severity of this issue we are not issuing new releases ofOpenSSL at this time. The fix will be included in the next releases when theybecome available. (CVE-2024-5535)\",\n    \"cvss\": [],\n    \"fix\": {\n      \"versions\": [\n        \"1.0.2k-24.amzn2.0.13\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2024-5535\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-5535\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"Critical\",\n      \"urls\": [\n        \"http://www.openwall.com/lists/oss-security/2024/06/27/1\",\n        \"http://www.openwall.com/lists/oss-security/2024/06/28/4\",\n        \"https://github.com/openssl/openssl/commit/4ada436a1946cbb24db5ab4ca082b69c1bc10f37\",\n        \"https://github.com/openssl/openssl/commit/99fb785a5f85315b95288921a321a935ea29a51e\",\n        \"https://github.com/openssl/openssl/commit/cf6f91f6121f4db167405db2f0de410a456f260c\",\n        \"https://github.com/openssl/openssl/commit/e86ac436f0bd54d4517745483e2315650fae7b2c\",\n        \"https://github.openssl.org/openssl/extended-releases/commit/9947251413065a05189a63c9b7a6c1d4e224c21c\",\n        \"https://github.openssl.org/openssl/extended-releases/commit/b78ec0824da857223486660177d3b1f255c65d87\",\n        \"https://security.netapp.com/advisory/ntap-20240712-0005/\",\n        \"https://www.openssl.org/news/secadv/20240627.txt\"\n      ],\n      \"description\": \"Issue summary: Calling the OpenSSL API function SSL_select_next_proto with an\\nempty supported client protocols buffer may cause a crash or memory contents to\\nbe sent to the peer.\\n\\nImpact summary: A buffer overread can have a range of potential consequences\\nsuch as unexpected application beahviour or a crash. In particular this issue\\ncould result in up to 255 bytes of arbitrary private data from memory being sent\\nto the peer leading to a loss of confidentiality. However, only applications\\nthat directly call the SSL_select_next_proto function with a 0 length list of\\nsupported client protocols are affected by this issue. This would normally never\\nbe a valid scenario and is typically not under attacker control but may occur by\\naccident in the case of a configuration or programming error in the calling\\napplication.\\n\\nThe OpenSSL API function SSL_select_next_proto is typically used by TLS\\napplications that support ALPN (Application Layer Protocol Negotiation) or NPN\\n(Next Protocol Negotiation). NPN is older, was never standardised and\\nis deprecated in favour of ALPN. We believe that ALPN is significantly more\\nwidely deployed than NPN. The SSL_select_next_proto function accepts a list of\\nprotocols from the server and a list of protocols from the client and returns\\nthe first protocol that appears in the server list that also appears in the\\nclient list. In the case of no overlap between the two lists it returns the\\nfirst item in the client list. In either case it will signal whether an overlap\\nbetween the two lists was found. In the case where SSL_select_next_proto is\\ncalled with a zero length client list it fails to notice this condition and\\nreturns the memory immediately following the client list pointer (and reports\\nthat there was no overlap in the lists).\\n\\nThis function is typically called from a server side application callback for\\nALPN or a client side application callback for NPN. In the case of ALPN the list\\nof protocols supplied by the client is guaranteed by libssl to never be zero in\\nlength. The list of server protocols comes from the application and should never\\nnormally be expected to be of zero length. In this case if the\\nSSL_select_next_proto function has been called as expected (with the list\\nsupplied by the client passed in the client/client_len parameters), then the\\napplication will not be vulnerable to this issue. If the application has\\naccidentally been configured with a zero length server list, and has\\naccidentally passed that zero length server list in the client/client_len\\nparameters, and has additionally failed to correctly handle a \\\"no overlap\\\"\\nresponse (which would normally result in a handshake failure in ALPN) then it\\nwill be vulnerable to this problem.\\n\\nIn the case of NPN, the protocol permits the client to opportunistically select\\na protocol when there is no overlap. OpenSSL returns the first client protocol\\nin the no overlap case in support of this. The list of client protocols comes\\nfrom the application and should never normally be expected to be of zero length.\\nHowever if the SSL_select_next_proto function is accidentally called with a\\nclient_len of 0 then an invalid memory pointer will be returned instead. If the\\napplication uses this output as the opportunistic protocol then the loss of\\nconfidentiality will occur.\\n\\nThis issue has been assessed as Low severity because applications are most\\nlikely to be vulnerable if they are using NPN instead of ALPN - but NPN is not\\nwidely used. It also requires an application configuration or programming error.\\nFinally, this issue would not typically be under attacker control making active\\nexploitation unlikely.\\n\\nThe FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.\\n\\nDue to the low severity of this issue we are not issuing new releases of\\nOpenSSL at this time. The fix will be included in the next releases when they\\nbecome available.\",\n      \"cvss\": [\n        {\n          \"source\": \"134c704f-9b21-4f2e-91b3-4a467353bcc0\",\n          \"type\": \"Secondary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H\",\n          \"metrics\": {\n            \"baseScore\": 9.1,\n            \"exploitabilityScore\": 3.9,\n            \"impactScore\": 5.2\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"rpm-matcher\",\n    \"searchedBy\": {\n      \"distro\": {\n        \"type\": \"amazonlinux\",\n        \"version\": \"2\"\n      },\n      \"namespace\": \"amazon:distro:amazonlinux:2\",\n      \"package\": {\n        \"name\": \"openssl-libs\",\n        \"version\": \"1:1.0.2k-24.amzn2.0.12\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"< 1.0.2k-24.amzn2.0.13 (rpm)\",\n      \"vulnerabilityID\": \"ALAS-2024-2604\"\n    }\n  },\n  {\n    \"type\": \"exact-indirect-match\",\n    \"matcher\": \"rpm-matcher\",\n    \"searchedBy\": {\n      \"distro\": {\n        \"type\": \"amazonlinux\",\n        \"version\": \"2\"\n      },\n      \"namespace\": \"amazon:distro:amazonlinux:2\",\n      \"package\": {\n        \"name\": \"openssl\",\n        \"version\": \"1.0.2k-24.amzn2.0.12\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"< 1.0.2k-24.amzn2.0.13 (rpm)\",\n      \"vulnerabilityID\": \"ALAS-2024-2604\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"ca07aa6bdda5c274\",\n  \"name\": \"openssl-libs\",\n  \"version\": \"1:1.0.2k-24.amzn2.0.12\",\n  \"type\": \"rpm\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lib/rpm/Packages\",\n      \"layerID\": \"sha256:0044b36762beca646f20eb6730e3575ec671a8857b39485f38ba0e715d375483\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [\n    \"OpenSSL\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:openssl-libs:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:openssl-libs:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:openssl_libs:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:openssl_libs:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:amazonlinux:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:amazonlinux:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:openssl:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:openssl:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:rpm/amzn/openssl-libs@1.0.2k-24.amzn2.0.12?arch=aarch64&epoch=1&upstream=openssl-1.0.2k-24.amzn2.0.12.src.rpm&distro=amzn-2\",\n  \"upstreams\": [\n    {\n      \"name\": \"openssl\",\n      \"version\": \"1.0.2k-24.amzn2.0.12\"\n    }\n  ],\n  \"metadataType\": \"RpmMetadata\",\n  \"metadata\": {\n    \"epoch\": 1,\n    \"modularityLabel\": \"\"\n  }\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "GHSA-mq26-g339-26xf",
            "severity": "Medium"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 23.3",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/advisories/GHSA-mq26-g339-26xf"
            },
            {
              "url": "https://github.com/pypa/pip/pull/12306"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to GHSA-mq26-g339-26xf in cloudwatch_to_s3:latest",
          "id": "Grype/GHSA-mq26-g339-26xf",
          "desc": "Command Injection in pip when used with Mercurial",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"GHSA-mq26-g339-26xf\",\n    \"dataSource\": \"https://github.com/advisories/GHSA-mq26-g339-26xf\",\n    \"namespace\": \"github:language:python\",\n    \"severity\": \"Medium\",\n    \"urls\": [\n      \"https://github.com/advisories/GHSA-mq26-g339-26xf\"\n    ],\n    \"description\": \"Command Injection in pip when used with Mercurial\",\n    \"cvss\": [\n      {\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N\",\n        \"metrics\": {\n          \"baseScore\": 5.5,\n          \"exploitabilityScore\": 1.8,\n          \"impactScore\": 3.6\n        },\n        \"vendorMetadata\": {\n          \"base_severity\": \"Medium\",\n          \"status\": \"N/A\"\n        }\n      }\n    ],\n    \"fix\": {\n      \"versions\": [\n        \"23.3\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2023-5752\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2023-5752\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"Low\",\n      \"urls\": [\n        \"https://github.com/pypa/pip/pull/12306\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/\",\n        \"https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/\"\n      ],\n      \"description\": \"When installing a package from a Mercurial VCS URL  (ie \\\"pip install \\nhg+...\\\") with pip prior to v23.3, the specified Mercurial revision could\\n be used to inject arbitrary configuration options to the \\\"hg clone\\\" \\ncall (ie \\\"--config\\\"). Controlling the Mercurial configuration can modify\\n how and which repository is installed. This vulnerability does not \\naffect users who aren't installing from Mercurial.\\n\",\n      \"cvss\": [\n        {\n          \"source\": \"nvd@nist.gov\",\n          \"type\": \"Primary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N\",\n          \"metrics\": {\n            \"baseScore\": 3.3,\n            \"exploitabilityScore\": 1.8,\n            \"impactScore\": 1.4\n          },\n          \"vendorMetadata\": {}\n        },\n        {\n          \"source\": \"cna@python.org\",\n          \"type\": \"Secondary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N\",\n          \"metrics\": {\n            \"baseScore\": 5.5,\n            \"exploitabilityScore\": 1.8,\n            \"impactScore\": 3.6\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"python-matcher\",\n    \"searchedBy\": {\n      \"language\": \"python\",\n      \"namespace\": \"github:language:python\",\n      \"package\": {\n        \"name\": \"pip\",\n        \"version\": \"23.0.1\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"<23.3 (python)\",\n      \"vulnerabilityID\": \"GHSA-mq26-g339-26xf\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"8cac57bcd656efc6\",\n  \"name\": \"pip\",\n  \"version\": \"23.0.1\",\n  \"type\": \"python\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/pip-23.0.1.dist-info/METADATA\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/pip-23.0.1.dist-info/RECORD\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/pip-23.0.1.dist-info/top_level.txt\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"python\",\n  \"licenses\": [\n    \"MIT\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:pip_developers_project:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developers_project:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sig_project:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sig_project:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developersproject:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developersproject:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sigproject:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sigproject:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developers_project:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sig_project:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developers:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developers:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developersproject:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils-sig:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils-sig:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sig:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sig:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sigproject:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python-pip:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python-pip:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python_pip:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python_pip:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip_developers:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils-sig:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:distutils_sig:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pypa:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pypa:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip:python-pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip:python_pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python-pip:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python_pip:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pypa:pip:23.0.1:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:pip:pip:23.0.1:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:pypi/pip@23.0.1\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-7592",
            "severity": "High"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/python/cpython/issues/123067"
            },
            {
              "url": "https://github.com/python/cpython/pull/123075"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-7592 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-7592",
          "desc": "There is a LOW severity vulnerability affecting CPython, specifically the\n'http.cookies' standard library module.\n\n\nWhen parsing cookies that contained backslashes for quoted characters in\nthe cookie value, the parser would use an algorithm with quadratic\ncomplexity, resulting in excess CPU resources being used while parsing the\nvalue.",
          "impact": 0.7,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-7592\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-7592\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"High\",\n    \"urls\": [\n      \"https://github.com/python/cpython/issues/123067\",\n      \"https://github.com/python/cpython/pull/123075\",\n      \"https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/\"\n    ],\n    \"description\": \"There is a LOW severity vulnerability affecting CPython, specifically the\\n'http.cookies' standard library module.\\n\\n\\nWhen parsing cookies that contained backslashes for quoted characters in\\nthe cookie value, the parser would use an algorithm with quadratic\\ncomplexity, resulting in excess CPU resources being used while parsing the\\nvalue.\",\n    \"cvss\": [\n      {\n        \"source\": \"nvd@nist.gov\",\n        \"type\": \"Primary\",\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H\",\n        \"metrics\": {\n          \"baseScore\": 7.5,\n          \"exploitabilityScore\": 3.9,\n          \"impactScore\": 3.6\n        },\n        \"vendorMetadata\": {}\n      }\n    ],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-7592\",\n      \"versionConstraint\": \"<= 3.13.0 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-0397",
            "severity": "High"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "http://www.openwall.com/lists/oss-security/2024/06/17/2"
            },
            {
              "url": "https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d"
            },
            {
              "url": "https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524"
            },
            {
              "url": "https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e"
            },
            {
              "url": "https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286"
            },
            {
              "url": "https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa"
            },
            {
              "url": "https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab"
            },
            {
              "url": "https://github.com/python/cpython/issues/114572"
            },
            {
              "url": "https://github.com/python/cpython/pull/114573"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-0397 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-0397",
          "desc": "A defect was discovered in the Python “ssl” module where there is a memory\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\n“get_ca_certs()”. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
          "impact": 0.7,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-0397\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-0397\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"High\",\n    \"urls\": [\n      \"http://www.openwall.com/lists/oss-security/2024/06/17/2\",\n      \"https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d\",\n      \"https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524\",\n      \"https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e\",\n      \"https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286\",\n      \"https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa\",\n      \"https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab\",\n      \"https://github.com/python/cpython/issues/114572\",\n      \"https://github.com/python/cpython/pull/114573\",\n      \"https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/\"\n    ],\n    \"description\": \"A defect was discovered in the Python “ssl” module where there is a memory\\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\\n“get_ca_certs()”. The race condition can be triggered if the methods are\\ncalled at the same time as certificates are loaded into the SSLContext,\\nsuch as during the TLS handshake with a certificate directory configured.\\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.\",\n    \"cvss\": [\n      {\n        \"source\": \"134c704f-9b21-4f2e-91b3-4a467353bcc0\",\n        \"type\": \"Secondary\",\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H\",\n        \"metrics\": {\n          \"baseScore\": 7.4,\n          \"exploitabilityScore\": 2.2,\n          \"impactScore\": 5.2\n        },\n        \"vendorMetadata\": {}\n      }\n    ],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-0397\",\n      \"versionConstraint\": \">= 3.13.0a1, < 3.13.0a5 || >= 3.12.0, < 3.12.3 || >= 3.11.0, < 3.11.9 || < 3.10.14 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2023-36632",
            "severity": "High"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://docs.python.org/3/library/email.html"
            },
            {
              "url": "https://docs.python.org/3/library/email.utils.html"
            },
            {
              "url": "https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py"
            },
            {
              "url": "https://github.com/python/cpython/issues/103800"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2023-36632 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2023-36632",
          "desc": "The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.",
          "impact": 0.7,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2023-36632\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2023-36632\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"High\",\n    \"urls\": [\n      \"https://docs.python.org/3/library/email.html\",\n      \"https://docs.python.org/3/library/email.utils.html\",\n      \"https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py\",\n      \"https://github.com/python/cpython/issues/103800\"\n    ],\n    \"description\": \"The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \\\"RecursionError: maximum recursion depth exceeded while calling a Python object\\\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.\",\n    \"cvss\": [\n      {\n        \"source\": \"nvd@nist.gov\",\n        \"type\": \"Primary\",\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H\",\n        \"metrics\": {\n          \"baseScore\": 7.5,\n          \"exploitabilityScore\": 3.9,\n          \"impactScore\": 3.6\n        },\n        \"vendorMetadata\": {}\n      }\n    ],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2023-36632\",\n      \"versionConstraint\": \"<= 3.11.4 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-6923",
            "severity": "Medium"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7"
            },
            {
              "url": "https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0"
            },
            {
              "url": "https://github.com/python/cpython/issues/121650"
            },
            {
              "url": "https://github.com/python/cpython/pull/122233"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-6923 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-6923",
          "desc": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-6923\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-6923\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"Medium\",\n    \"urls\": [\n      \"https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7\",\n      \"https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0\",\n      \"https://github.com/python/cpython/issues/121650\",\n      \"https://github.com/python/cpython/pull/122233\",\n      \"https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/\"\n    ],\n    \"description\": \"There is a MEDIUM severity vulnerability affecting CPython.\\n\\nThe \\nemail module didn’t properly quote newlines for email headers when \\nserializing an email message allowing for header injection when an email\\n is serialized.\",\n    \"cvss\": [\n      {\n        \"source\": \"134c704f-9b21-4f2e-91b3-4a467353bcc0\",\n        \"type\": \"Secondary\",\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L\",\n        \"metrics\": {\n          \"baseScore\": 5.5,\n          \"exploitabilityScore\": 2.1,\n          \"impactScore\": 3.4\n        },\n        \"vendorMetadata\": {}\n      }\n    ],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-6923\",\n      \"versionConstraint\": \">= 3.13.0a1, <= 3.13.0rc2 || < 3.12.5 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2023-27043",
            "severity": "Medium"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "http://python.org"
            },
            {
              "url": "https://github.com/python/cpython/issues/102988"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/"
            },
            {
              "url": "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html"
            },
            {
              "url": "https://security.netapp.com/advisory/ntap-20230601-0003/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2023-27043 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2023-27043",
          "desc": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2023-27043\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2023-27043\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"Medium\",\n    \"urls\": [\n      \"http://python.org\",\n      \"https://github.com/python/cpython/issues/102988\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/\",\n      \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/\",\n      \"https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html\",\n      \"https://security.netapp.com/advisory/ntap-20230601-0003/\"\n    ],\n    \"description\": \"The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.\",\n    \"cvss\": [\n      {\n        \"source\": \"nvd@nist.gov\",\n        \"type\": \"Primary\",\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N\",\n        \"metrics\": {\n          \"baseScore\": 5.3,\n          \"exploitabilityScore\": 3.9,\n          \"impactScore\": 1.4\n        },\n        \"vendorMetadata\": {}\n      }\n    ],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2023-27043\",\n      \"versionConstraint\": \"<= 2.7.18 || >= 3.0, <= 3.11 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-8088",
            "severity": "Unknown"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e"
            },
            {
              "url": "https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64"
            },
            {
              "url": "https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea"
            },
            {
              "url": "https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db"
            },
            {
              "url": "https://github.com/python/cpython/issues/122905"
            },
            {
              "url": "https://github.com/python/cpython/issues/123270"
            },
            {
              "url": "https://github.com/python/cpython/pull/122906"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-8088 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-8088",
          "desc": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-8088\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-8088\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"Unknown\",\n    \"urls\": [\n      \"https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e\",\n      \"https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64\",\n      \"https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea\",\n      \"https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db\",\n      \"https://github.com/python/cpython/issues/122905\",\n      \"https://github.com/python/cpython/issues/123270\",\n      \"https://github.com/python/cpython/pull/122906\",\n      \"https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/\"\n    ],\n    \"description\": \"There is a HIGH severity vulnerability affecting the CPython \\\"zipfile\\\"\\nmodule affecting \\\"zipfile.Path\\\". Note that the more common API \\\"zipfile.ZipFile\\\" class is unaffected.\\n\\n\\n\\n\\n\\nWhen iterating over names of entries in a zip archive (for example, methods\\nof \\\"zipfile.Path\\\" like \\\"namelist()\\\", \\\"iterdir()\\\", etc)\\nthe process can be put into an infinite loop with a maliciously crafted\\nzip archive. This defect applies when reading only metadata or extracting\\nthe contents of the zip archive. Programs that are not handling\\nuser-controlled zip archives are not affected.\",\n    \"cvss\": [],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "skipped",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-8088\",\n      \"versionConstraint\": \"<= 3.13.0 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00",
              "skip_message": "Manual review required because a Anchore Grype rating severity is set to `negligible` or `unknown`."
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-5642",
            "severity": "Unknown"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "http://www.openwall.com/lists/oss-security/2024/06/28/4"
            },
            {
              "url": "https://github.com/python/cpython/commit/39258d3595300bc7b952854c915f63ae2d4b9c3e"
            },
            {
              "url": "https://github.com/python/cpython/issues/121227"
            },
            {
              "url": "https://github.com/python/cpython/pull/23014"
            },
            {
              "url": "https://jbp.io/2024/06/27/cve-2024-5535-openssl-memory-safety.html"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/"
            },
            {
              "url": "https://security.netapp.com/advisory/ntap-20240726-0005/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-5642 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-5642",
          "desc": "CPython 3.9 and earlier doesn't disallow configuring an empty list (\"[]\") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-5642\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-5642\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"Unknown\",\n    \"urls\": [\n      \"http://www.openwall.com/lists/oss-security/2024/06/28/4\",\n      \"https://github.com/python/cpython/commit/39258d3595300bc7b952854c915f63ae2d4b9c3e\",\n      \"https://github.com/python/cpython/issues/121227\",\n      \"https://github.com/python/cpython/pull/23014\",\n      \"https://jbp.io/2024/06/27/cve-2024-5535-openssl-memory-safety.html\",\n      \"https://mail.python.org/archives/list/security-announce@python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/\",\n      \"https://security.netapp.com/advisory/ntap-20240726-0005/\"\n    ],\n    \"description\": \"CPython 3.9 and earlier doesn't disallow configuring an empty list (\\\"[]\\\") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).\",\n    \"cvss\": [],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "skipped",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-5642\",\n      \"versionConstraint\": \"< 3.10.0b1 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00",
              "skip_message": "Manual review required because a Anchore Grype rating severity is set to `negligible` or `unknown`."
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-4032",
            "severity": "Unknown"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "http://www.openwall.com/lists/oss-security/2024/06/17/3"
            },
            {
              "url": "https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8"
            },
            {
              "url": "https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f"
            },
            {
              "url": "https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3"
            },
            {
              "url": "https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb"
            },
            {
              "url": "https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906"
            },
            {
              "url": "https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3"
            },
            {
              "url": "https://github.com/python/cpython/issues/113171"
            },
            {
              "url": "https://github.com/python/cpython/pull/113179"
            },
            {
              "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/"
            },
            {
              "url": "https://security.netapp.com/advisory/ntap-20240726-0004/"
            },
            {
              "url": "https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml"
            },
            {
              "url": "https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-4032 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-4032",
          "desc": "The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-4032\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-4032\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"Unknown\",\n    \"urls\": [\n      \"http://www.openwall.com/lists/oss-security/2024/06/17/3\",\n      \"https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8\",\n      \"https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f\",\n      \"https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3\",\n      \"https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb\",\n      \"https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906\",\n      \"https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3\",\n      \"https://github.com/python/cpython/issues/113171\",\n      \"https://github.com/python/cpython/pull/113179\",\n      \"https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/\",\n      \"https://security.netapp.com/advisory/ntap-20240726-0004/\",\n      \"https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml\",\n      \"https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml\"\n    ],\n    \"description\": \"The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\\n\\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.\",\n    \"cvss\": [],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "skipped",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"stock-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"python\",\n        \"version\": \"3.9.19\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-4032\",\n      \"versionConstraint\": \"< 3.12.4 || >= 3.13.0a1, < 3.13.0a6 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"a120648b38c61b3b\",\n  \"name\": \"python\",\n  \"version\": \"3.9.19\",\n  \"type\": \"binary\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/bin/python3.9\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/libpython3.9.so.1.0\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"\",\n  \"licenses\": [],\n  \"cpes\": [\n    \"cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\",\n    \"cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:generic/python@3.9.19\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00",
              "skip_message": "Manual review required because a Anchore Grype rating severity is set to `negligible` or `unknown`."
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "GHSA-r9hx-vwmv-q579",
            "severity": "High"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 65.5.1",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/advisories/GHSA-r9hx-vwmv-q579"
            },
            {
              "url": "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200"
            },
            {
              "url": "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be"
            },
            {
              "url": "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/"
            },
            {
              "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/"
            },
            {
              "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
            },
            {
              "url": "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/"
            },
            {
              "url": "https://security.netapp.com/advisory/ntap-20230214-0001/"
            },
            {
              "url": "https://security.netapp.com/advisory/ntap-20240621-0006/"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to GHSA-r9hx-vwmv-q579 in cloudwatch_to_s3:latest",
          "id": "Grype/GHSA-r9hx-vwmv-q579",
          "desc": "pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)",
          "impact": 0.7,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"GHSA-r9hx-vwmv-q579\",\n    \"dataSource\": \"https://github.com/advisories/GHSA-r9hx-vwmv-q579\",\n    \"namespace\": \"github:language:python\",\n    \"severity\": \"High\",\n    \"urls\": [\n      \"https://github.com/advisories/GHSA-r9hx-vwmv-q579\"\n    ],\n    \"description\": \"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)\",\n    \"cvss\": [\n      {\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H\",\n        \"metrics\": {\n          \"baseScore\": 7.5,\n          \"exploitabilityScore\": 3.9,\n          \"impactScore\": 3.6\n        },\n        \"vendorMetadata\": {\n          \"base_severity\": \"High\",\n          \"status\": \"N/A\"\n        }\n      }\n    ],\n    \"fix\": {\n      \"versions\": [\n        \"65.5.1\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2022-40897\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2022-40897\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"Medium\",\n      \"urls\": [\n        \"https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200\",\n        \"https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be\",\n        \"https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/\",\n        \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/\",\n        \"https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/\",\n        \"https://pyup.io/vulnerabilities/CVE-2022-40897/52495/\",\n        \"https://security.netapp.com/advisory/ntap-20230214-0001/\",\n        \"https://security.netapp.com/advisory/ntap-20240621-0006/\"\n      ],\n      \"description\": \"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.\",\n      \"cvss\": [\n        {\n          \"source\": \"nvd@nist.gov\",\n          \"type\": \"Primary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H\",\n          \"metrics\": {\n            \"baseScore\": 5.9,\n            \"exploitabilityScore\": 2.2,\n            \"impactScore\": 3.6\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"python-matcher\",\n    \"searchedBy\": {\n      \"language\": \"python\",\n      \"namespace\": \"github:language:python\",\n      \"package\": {\n        \"name\": \"setuptools\",\n        \"version\": \"58.1.0\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"<65.5.1 (python)\",\n      \"vulnerabilityID\": \"GHSA-r9hx-vwmv-q579\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"bc6c39be42a59eb7\",\n  \"name\": \"setuptools\",\n  \"version\": \"58.1.0\",\n  \"type\": \"python\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/METADATA\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/RECORD\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/top_level.txt\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"python\",\n  \"licenses\": [\n    \"UNKNOWN\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:python:setuptools:58.1.0:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:pypi/setuptools@58.1.0\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "GHSA-cx63-2mw6-8hw5",
            "severity": "High"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 70.0.0",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/advisories/GHSA-cx63-2mw6-8hw5"
            },
            {
              "url": "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0"
            },
            {
              "url": "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to GHSA-cx63-2mw6-8hw5 in cloudwatch_to_s3:latest",
          "id": "Grype/GHSA-cx63-2mw6-8hw5",
          "desc": "setuptools vulnerable to Command Injection via package URL",
          "impact": 0.7,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"GHSA-cx63-2mw6-8hw5\",\n    \"dataSource\": \"https://github.com/advisories/GHSA-cx63-2mw6-8hw5\",\n    \"namespace\": \"github:language:python\",\n    \"severity\": \"High\",\n    \"urls\": [\n      \"https://github.com/advisories/GHSA-cx63-2mw6-8hw5\"\n    ],\n    \"description\": \"setuptools vulnerable to Command Injection via package URL\",\n    \"cvss\": [\n      {\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H\",\n        \"metrics\": {\n          \"baseScore\": 8.8,\n          \"exploitabilityScore\": 2.8,\n          \"impactScore\": 5.9\n        },\n        \"vendorMetadata\": {\n          \"base_severity\": \"High\",\n          \"status\": \"N/A\"\n        }\n      }\n    ],\n    \"fix\": {\n      \"versions\": [\n        \"70.0.0\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2024-6345\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-6345\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"High\",\n      \"urls\": [\n        \"https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0\",\n        \"https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5\"\n      ],\n      \"description\": \"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.\",\n      \"cvss\": [\n        {\n          \"source\": \"security@huntr.dev\",\n          \"type\": \"Secondary\",\n          \"version\": \"3.0\",\n          \"vector\": \"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H\",\n          \"metrics\": {\n            \"baseScore\": 8.8,\n            \"exploitabilityScore\": 2.8,\n            \"impactScore\": 5.9\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"python-matcher\",\n    \"searchedBy\": {\n      \"language\": \"python\",\n      \"namespace\": \"github:language:python\",\n      \"package\": {\n        \"name\": \"setuptools\",\n        \"version\": \"58.1.0\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"<70.0.0 (python)\",\n      \"vulnerabilityID\": \"GHSA-cx63-2mw6-8hw5\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"bc6c39be42a59eb7\",\n  \"name\": \"setuptools\",\n  \"version\": \"58.1.0\",\n  \"type\": \"python\",\n  \"locations\": [\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/METADATA\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/RECORD\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    },\n    {\n      \"path\": \"/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/top_level.txt\",\n      \"layerID\": \"sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0\"\n    }\n  ],\n  \"language\": \"python\",\n  \"licenses\": [\n    \"UNKNOWN\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:python:setuptools:58.1.0:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:pypi/setuptools@58.1.0\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "CVE-2024-24791",
            "severity": "High"
          },
          "descriptions": [
            {
              "data": "vulnerability is not known to be fixed in any versions",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://go.dev/cl/591255"
            },
            {
              "url": "https://go.dev/issue/67555"
            },
            {
              "url": "https://groups.google.com/g/golang-dev/c/t0rK-qHBqzY/m/6MMoAZkMAgAJ"
            },
            {
              "url": "https://pkg.go.dev/vuln/GO-2024-2963"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to CVE-2024-24791 in cloudwatch_to_s3:latest",
          "id": "Grype/CVE-2024-24791",
          "desc": "The net/http HTTP/1.1 client mishandled the case where a server responds to a request with an \"Expect: 100-continue\" header with a non-informational (200 or higher) status. This mishandling could leave a client connection in an invalid state, where the next request sent on the connection will fail. An attacker sending a request to a net/http/httputil.ReverseProxy proxy can exploit this mishandling to cause a denial of service by sending \"Expect: 100-continue\" requests which elicit a non-informational response from the backend. Each such request leaves the proxy with an invalid connection, and causes one subsequent request using that connection to fail.",
          "impact": 0.7,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"CVE-2024-24791\",\n    \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-24791\",\n    \"namespace\": \"nvd:cpe\",\n    \"severity\": \"High\",\n    \"urls\": [\n      \"https://go.dev/cl/591255\",\n      \"https://go.dev/issue/67555\",\n      \"https://groups.google.com/g/golang-dev/c/t0rK-qHBqzY/m/6MMoAZkMAgAJ\",\n      \"https://pkg.go.dev/vuln/GO-2024-2963\"\n    ],\n    \"description\": \"The net/http HTTP/1.1 client mishandled the case where a server responds to a request with an \\\"Expect: 100-continue\\\" header with a non-informational (200 or higher) status. This mishandling could leave a client connection in an invalid state, where the next request sent on the connection will fail. An attacker sending a request to a net/http/httputil.ReverseProxy proxy can exploit this mishandling to cause a denial of service by sending \\\"Expect: 100-continue\\\" requests which elicit a non-informational response from the backend. Each such request leaves the proxy with an invalid connection, and causes one subsequent request using that connection to fail.\",\n    \"cvss\": [\n      {\n        \"source\": \"134c704f-9b21-4f2e-91b3-4a467353bcc0\",\n        \"type\": \"Secondary\",\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H\",\n        \"metrics\": {\n          \"baseScore\": 7.5,\n          \"exploitabilityScore\": 3.9,\n          \"impactScore\": 3.6\n        },\n        \"vendorMetadata\": {}\n      }\n    ],\n    \"fix\": {\n      \"versions\": [],\n      \"state\": \"unknown\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": []\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"cpe-match\",\n    \"matcher\": \"go-module-matcher\",\n    \"searchedBy\": {\n      \"namespace\": \"nvd:cpe\",\n      \"cpes\": [\n        \"cpe:2.3:a:golang:go:1.22.4:-:*:*:*:*:*:*\"\n      ],\n      \"package\": {\n        \"name\": \"stdlib\",\n        \"version\": \"go1.22.4\"\n      }\n    },\n    \"found\": {\n      \"vulnerabilityID\": \"CVE-2024-24791\",\n      \"versionConstraint\": \"< 1.21.12 || >= 1.22.0-0, < 1.22.5 (unknown)\",\n      \"cpes\": [\n        \"cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*\"\n      ]\n    }\n  }\n]",
              "message": "{\n  \"id\": \"c93538cbf3d8e93b\",\n  \"name\": \"stdlib\",\n  \"version\": \"go1.22.4\",\n  \"type\": \"go-module\",\n  \"locations\": [\n    {\n      \"path\": \"/usr/local/bin/aws-lambda-rie\",\n      \"layerID\": \"sha256:9a9b5814afc2b76039ada8e0f4445eeec0c487bcf7637b36b20a7f25bb15b369\"\n    }\n  ],\n  \"language\": \"go\",\n  \"licenses\": [\n    \"BSD-3-Clause\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:golang:go:1.22.4:-:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:golang/stdlib@1.22.4\",\n  \"upstreams\": [],\n  \"metadataType\": \"GolangBinMetadata\",\n  \"metadata\": {\n    \"goCompiledVersion\": \"go1.22.4\",\n    \"architecture\": \"\"\n  }\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        },
        {
          "tags": {
            "nist": [
              "SA-11",
              "RA-5"
            ],
            "cveid": "GHSA-34jh-p97f-mpxf",
            "severity": "Medium"
          },
          "descriptions": [
            {
              "data": "vulnerability is fixed for versions 1.26.19",
              "label": "fix"
            },
            {
              "data": "undefined",
              "label": "check"
            }
          ],
          "refs": [
            {
              "url": "https://github.com/advisories/GHSA-34jh-p97f-mpxf"
            },
            {
              "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
            },
            {
              "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
            }
          ],
          "source_location": {},
          "title": "Grype found a vulnerability to GHSA-34jh-p97f-mpxf in cloudwatch_to_s3:latest",
          "id": "Grype/GHSA-34jh-p97f-mpxf",
          "desc": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects ",
          "impact": 0.5,
          "code": "{\n  \"vulnerability\": {\n    \"id\": \"GHSA-34jh-p97f-mpxf\",\n    \"dataSource\": \"https://github.com/advisories/GHSA-34jh-p97f-mpxf\",\n    \"namespace\": \"github:language:python\",\n    \"severity\": \"Medium\",\n    \"urls\": [\n      \"https://github.com/advisories/GHSA-34jh-p97f-mpxf\"\n    ],\n    \"description\": \"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects \",\n    \"cvss\": [\n      {\n        \"version\": \"3.1\",\n        \"vector\": \"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N\",\n        \"metrics\": {\n          \"baseScore\": 4.4,\n          \"exploitabilityScore\": 0.7,\n          \"impactScore\": 3.6\n        },\n        \"vendorMetadata\": {\n          \"base_severity\": \"Medium\",\n          \"status\": \"N/A\"\n        }\n      }\n    ],\n    \"fix\": {\n      \"versions\": [\n        \"1.26.19\"\n      ],\n      \"state\": \"fixed\"\n    },\n    \"advisories\": []\n  },\n  \"relatedVulnerabilities\": [\n    {\n      \"id\": \"CVE-2024-37891\",\n      \"dataSource\": \"https://nvd.nist.gov/vuln/detail/CVE-2024-37891\",\n      \"namespace\": \"nvd:cpe\",\n      \"severity\": \"Medium\",\n      \"urls\": [\n        \"https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e\",\n        \"https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf\"\n      ],\n      \"description\": \" urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.\",\n      \"cvss\": [\n        {\n          \"source\": \"security-advisories@github.com\",\n          \"type\": \"Secondary\",\n          \"version\": \"3.1\",\n          \"vector\": \"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N\",\n          \"metrics\": {\n            \"baseScore\": 4.4,\n            \"exploitabilityScore\": 0.7,\n            \"impactScore\": 3.6\n          },\n          \"vendorMetadata\": {}\n        }\n      ]\n    }\n  ]\n}",
          "results": [
            {
              "status": "failed",
              "code_desc": "[\n  {\n    \"type\": \"exact-direct-match\",\n    \"matcher\": \"python-matcher\",\n    \"searchedBy\": {\n      \"language\": \"python\",\n      \"namespace\": \"github:language:python\",\n      \"package\": {\n        \"name\": \"urllib3\",\n        \"version\": \"1.26.18\"\n      }\n    },\n    \"found\": {\n      \"versionConstraint\": \"<1.26.19 (python)\",\n      \"vulnerabilityID\": \"GHSA-34jh-p97f-mpxf\"\n    }\n  }\n]",
              "message": "{\n  \"id\": \"18a6c87286e142af\",\n  \"name\": \"urllib3\",\n  \"version\": \"1.26.18\",\n  \"type\": \"python\",\n  \"locations\": [\n    {\n      \"path\": \"/var/runtime/urllib3-1.26.18.dist-info/METADATA\",\n      \"layerID\": \"sha256:734a487fcc033d64cea626bc74e5937eda7014ad9b80d4b3af36f5cce52d2b03\"\n    },\n    {\n      \"path\": \"/var/runtime/urllib3-1.26.18.dist-info/RECORD\",\n      \"layerID\": \"sha256:734a487fcc033d64cea626bc74e5937eda7014ad9b80d4b3af36f5cce52d2b03\"\n    },\n    {\n      \"path\": \"/var/runtime/urllib3-1.26.18.dist-info/top_level.txt\",\n      \"layerID\": \"sha256:734a487fcc033d64cea626bc74e5937eda7014ad9b80d4b3af36f5cce52d2b03\"\n    }\n  ],\n  \"language\": \"python\",\n  \"licenses\": [\n    \"MIT\"\n  ],\n  \"cpes\": [\n    \"cpe:2.3:a:python:urllib3:1.26.18:*:*:*:*:*:*:*\"\n  ],\n  \"purl\": \"pkg:pypi/urllib3@1.26.18\",\n  \"upstreams\": []\n}",
              "start_time": "2024-08-29T13:47:41.623667-04:00"
            }
          ]
        }
      ],
      "sha256": "2170ec5567c87f86622f3c24c3f21c220ac81773ca25a481e17cd64cab559fee"
    }
  ],
  "passthrough": {
    "auxiliary_data": [
      {
        "name": "",
        "data": {}
      }
    ],
    "raw": {
      "wrapper": {
        "matches": [
          {
            "vulnerability": {
              "id": "ALAS-2024-2607",
              "dataSource": "https://alas.aws.amazon.com/AL2/ALAS-2024-2607.html",
              "namespace": "amazon:distro:amazonlinux:2",
              "severity": "Low",
              "urls": [
                "https://alas.aws.amazon.com/AL2/ALAS-2024-2607.html"
              ],
              "description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.05.30 and prior to 2024.07.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.07.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\" (CVE-2024-39689)",
              "cvss": [],
              "fix": {
                "versions": [
                  "2023.2.68-1.amzn2.0.1"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2024-39689",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-39689",
                "namespace": "nvd:cpe",
                "severity": "High",
                "urls": [
                  "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463",
                  "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc",
                  "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
                ],
                "description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.05.30 and prior to 2024.07.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.07.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"",
                "cvss": [
                  {
                    "source": "security-advisories@github.com",
                    "type": "Secondary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                    "metrics": {
                      "baseScore": 7.5,
                      "exploitabilityScore": 3.9,
                      "impactScore": 3.6
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "rpm-matcher",
                "searchedBy": {
                  "distro": {
                    "type": "amazonlinux",
                    "version": "2"
                  },
                  "namespace": "amazon:distro:amazonlinux:2",
                  "package": {
                    "name": "ca-certificates",
                    "version": "0:2023.2.64-1.amzn2.0.1"
                  }
                },
                "found": {
                  "versionConstraint": "< 2023.2.68-1.amzn2.0.1 (rpm)",
                  "vulnerabilityID": "ALAS-2024-2607"
                }
              }
            ],
            "artifact": {
              "id": "3fdee4f2791be89b",
              "name": "ca-certificates",
              "version": "2023.2.64-1.amzn2.0.1",
              "type": "rpm",
              "locations": [
                {
                  "path": "/var/lib/rpm/Packages",
                  "layerID": "sha256:0044b36762beca646f20eb6730e3575ec671a8857b39485f38ba0e715d375483"
                }
              ],
              "language": "",
              "licenses": [
                "Public Domain"
              ],
              "cpes": [
                "cpe:2.3:a:ca-certificates:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:ca-certificates:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:ca_certificates:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:ca_certificates:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:amazonlinux:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:amazonlinux:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:ca:ca-certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:ca:ca_certificates:2023.2.64-1.amzn2.0.1:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:rpm/amzn/ca-certificates@2023.2.64-1.amzn2.0.1?arch=noarch&upstream=ca-certificates-2023.2.64-1.amzn2.0.1.src.rpm&distro=amzn-2",
              "upstreams": [],
              "metadataType": "RpmMetadata",
              "metadata": {
                "epoch": null,
                "modularityLabel": ""
              }
            }
          },
          {
            "vulnerability": {
              "id": "ALAS-2024-2595",
              "dataSource": "https://alas.aws.amazon.com/AL2/ALAS-2024-2595.html",
              "namespace": "amazon:distro:amazonlinux:2",
              "severity": "Medium",
              "urls": [
                "https://alas.aws.amazon.com/AL2/ALAS-2024-2595.html"
              ],
              "description": "krb5: GSS message token handling (CVE-2024-37370)In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can cause invalid memory reads during GSS message token handling by sending message tokens with invalid length fields. (CVE-2024-37371)",
              "cvss": [],
              "fix": {
                "versions": [
                  "1.15.1-55.amzn2.2.8"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2024-37370",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-37370",
                "namespace": "nvd:cpe",
                "severity": "High",
                "urls": [
                  "https://github.com/krb5/krb5/commit/55fbf435edbe2e92dd8101669b1ce7144bc96fef",
                  "https://web.mit.edu/kerberos/www/advisories/"
                ],
                "description": "In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can modify the plaintext Extra Count field of a confidential GSS krb5 wrap token, causing the unwrapped token to appear truncated to the application.",
                "cvss": [
                  {
                    "source": "nvd@nist.gov",
                    "type": "Primary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                    "metrics": {
                      "baseScore": 7.5,
                      "exploitabilityScore": 3.9,
                      "impactScore": 3.6
                    },
                    "vendorMetadata": {}
                  }
                ]
              },
              {
                "id": "CVE-2024-37371",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-37371",
                "namespace": "nvd:cpe",
                "severity": "Critical",
                "urls": [
                  "https://github.com/krb5/krb5/commit/55fbf435edbe2e92dd8101669b1ce7144bc96fef",
                  "https://web.mit.edu/kerberos/www/advisories/"
                ],
                "description": "In MIT Kerberos 5 (aka krb5) before 1.21.3, an attacker can cause invalid memory reads during GSS message token handling by sending message tokens with invalid length fields.",
                "cvss": [
                  {
                    "source": "nvd@nist.gov",
                    "type": "Primary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
                    "metrics": {
                      "baseScore": 9.1,
                      "exploitabilityScore": 3.9,
                      "impactScore": 5.2
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "rpm-matcher",
                "searchedBy": {
                  "distro": {
                    "type": "amazonlinux",
                    "version": "2"
                  },
                  "namespace": "amazon:distro:amazonlinux:2",
                  "package": {
                    "name": "krb5-libs",
                    "version": "0:1.15.1-55.amzn2.2.7"
                  }
                },
                "found": {
                  "versionConstraint": "< 1.15.1-55.amzn2.2.8 (rpm)",
                  "vulnerabilityID": "ALAS-2024-2595"
                }
              },
              {
                "type": "exact-indirect-match",
                "matcher": "rpm-matcher",
                "searchedBy": {
                  "distro": {
                    "type": "amazonlinux",
                    "version": "2"
                  },
                  "namespace": "amazon:distro:amazonlinux:2",
                  "package": {
                    "name": "krb5",
                    "version": "1.15.1-55.amzn2.2.7"
                  }
                },
                "found": {
                  "versionConstraint": "< 1.15.1-55.amzn2.2.8 (rpm)",
                  "vulnerabilityID": "ALAS-2024-2595"
                }
              }
            ],
            "artifact": {
              "id": "3bb967025c5652e0",
              "name": "krb5-libs",
              "version": "1.15.1-55.amzn2.2.7",
              "type": "rpm",
              "locations": [
                {
                  "path": "/var/lib/rpm/Packages",
                  "layerID": "sha256:0044b36762beca646f20eb6730e3575ec671a8857b39485f38ba0e715d375483"
                }
              ],
              "language": "",
              "licenses": [
                "MIT"
              ],
              "cpes": [
                "cpe:2.3:a:amazonlinux:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:amazonlinux:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:krb5-libs:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:krb5-libs:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:krb5_libs:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:krb5_libs:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:krb5:krb5-libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*",
                "cpe:2.3:a:krb5:krb5_libs:1.15.1-55.amzn2.2.7:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:rpm/amzn/krb5-libs@1.15.1-55.amzn2.2.7?arch=aarch64&upstream=krb5-1.15.1-55.amzn2.2.7.src.rpm&distro=amzn-2",
              "upstreams": [
                {
                  "name": "krb5",
                  "version": "1.15.1-55.amzn2.2.7"
                }
              ],
              "metadataType": "RpmMetadata",
              "metadata": {
                "epoch": null,
                "modularityLabel": ""
              }
            }
          },
          {
            "vulnerability": {
              "id": "ALAS-2024-2604",
              "dataSource": "https://alas.aws.amazon.com/AL2/ALAS-2024-2604.html",
              "namespace": "amazon:distro:amazonlinux:2",
              "severity": "Medium",
              "urls": [
                "https://alas.aws.amazon.com/AL2/ALAS-2024-2604.html"
              ],
              "description": "Issue summary: Calling the OpenSSL API function SSL_select_next_proto with anempty supported client protocols buffer may cause a crash or memory contents tobe sent to the peer.Impact summary: A buffer overread can have a range of potential consequencessuch as unexpected application beahviour or a crash. In particular this issuecould result in up to 255 bytes of arbitrary private data from memory being sentto the peer leading to a loss of confidentiality. However, only applicationsthat directly call the SSL_select_next_proto function with a 0 length list ofsupported client protocols are affected by this issue. This would normally neverbe a valid scenario and is typically not under attacker control but may occur byaccident in the case of a configuration or programming error in the callingapplication.The OpenSSL API function SSL_select_next_proto is typically used by TLSapplications that support ALPN (Application Layer Protocol Negotiation) or NPN(Next Protocol Negotiation). NPN is older, was never standardised andis deprecated in favour of ALPN. We believe that ALPN is significantly morewidely deployed than NPN. The SSL_select_next_proto function accepts a list ofprotocols from the server and a list of protocols from the client and returnsthe first protocol that appears in the server list that also appears in theclient list. In the case of no overlap between the two lists it returns thefirst item in the client list. In either case it will signal whether an overlapbetween the two lists was found. In the case where SSL_select_next_proto iscalled with a zero length client list it fails to notice this condition andreturns the memory immediately following the client list pointer (and reportsthat there was no overlap in the lists).This function is typically called from a server side application callback forALPN or a client side application callback for NPN. In the case of ALPN the listof protocols supplied by the client is guaranteed by libssl to never be zero inlength. The list of server protocols comes from the application and should nevernormally be expected to be of zero length. In this case if theSSL_select_next_proto function has been called as expected (with the listsupplied by the client passed in the client/client_len parameters), then theapplication will not be vulnerable to this issue. If the application hasaccidentally been configured with a zero length server list, and hasaccidentally passed that zero length server list in the client/client_lenparameters, and has additionally failed to correctly handle a \"no overlap\"response (which would normally result in a handshake failure in ALPN) then itwill be vulnerable to this problem.In the case of NPN, the protocol permits the client to opportunistically selecta protocol when there is no overlap. OpenSSL returns the first client protocolin the no overlap case in support of this. The list of client protocols comesfrom the application and should never normally be expected to be of zero length.However if the SSL_select_next_proto function is accidentally called with aclient_len of 0 then an invalid memory pointer will be returned instead. If theapplication uses this output as the opportunistic protocol then the loss ofconfidentiality will occur.This issue has been assessed as Low severity because applications are mostlikely to be vulnerable if they are using NPN instead of ALPN - but NPN is notwidely used. It also requires an application configuration or programming error.Finally, this issue would not typically be under attacker control making activeexploitation unlikely.The FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.Due to the low severity of this issue we are not issuing new releases ofOpenSSL at this time. The fix will be included in the next releases when theybecome available. (CVE-2024-5535)",
              "cvss": [],
              "fix": {
                "versions": [
                  "1.0.2k-24.amzn2.0.13"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2024-5535",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-5535",
                "namespace": "nvd:cpe",
                "severity": "Critical",
                "urls": [
                  "http://www.openwall.com/lists/oss-security/2024/06/27/1",
                  "http://www.openwall.com/lists/oss-security/2024/06/28/4",
                  "https://github.com/openssl/openssl/commit/4ada436a1946cbb24db5ab4ca082b69c1bc10f37",
                  "https://github.com/openssl/openssl/commit/99fb785a5f85315b95288921a321a935ea29a51e",
                  "https://github.com/openssl/openssl/commit/cf6f91f6121f4db167405db2f0de410a456f260c",
                  "https://github.com/openssl/openssl/commit/e86ac436f0bd54d4517745483e2315650fae7b2c",
                  "https://github.openssl.org/openssl/extended-releases/commit/9947251413065a05189a63c9b7a6c1d4e224c21c",
                  "https://github.openssl.org/openssl/extended-releases/commit/b78ec0824da857223486660177d3b1f255c65d87",
                  "https://security.netapp.com/advisory/ntap-20240712-0005/",
                  "https://www.openssl.org/news/secadv/20240627.txt"
                ],
                "description": "Issue summary: Calling the OpenSSL API function SSL_select_next_proto with an\nempty supported client protocols buffer may cause a crash or memory contents to\nbe sent to the peer.\n\nImpact summary: A buffer overread can have a range of potential consequences\nsuch as unexpected application beahviour or a crash. In particular this issue\ncould result in up to 255 bytes of arbitrary private data from memory being sent\nto the peer leading to a loss of confidentiality. However, only applications\nthat directly call the SSL_select_next_proto function with a 0 length list of\nsupported client protocols are affected by this issue. This would normally never\nbe a valid scenario and is typically not under attacker control but may occur by\naccident in the case of a configuration or programming error in the calling\napplication.\n\nThe OpenSSL API function SSL_select_next_proto is typically used by TLS\napplications that support ALPN (Application Layer Protocol Negotiation) or NPN\n(Next Protocol Negotiation). NPN is older, was never standardised and\nis deprecated in favour of ALPN. We believe that ALPN is significantly more\nwidely deployed than NPN. The SSL_select_next_proto function accepts a list of\nprotocols from the server and a list of protocols from the client and returns\nthe first protocol that appears in the server list that also appears in the\nclient list. In the case of no overlap between the two lists it returns the\nfirst item in the client list. In either case it will signal whether an overlap\nbetween the two lists was found. In the case where SSL_select_next_proto is\ncalled with a zero length client list it fails to notice this condition and\nreturns the memory immediately following the client list pointer (and reports\nthat there was no overlap in the lists).\n\nThis function is typically called from a server side application callback for\nALPN or a client side application callback for NPN. In the case of ALPN the list\nof protocols supplied by the client is guaranteed by libssl to never be zero in\nlength. The list of server protocols comes from the application and should never\nnormally be expected to be of zero length. In this case if the\nSSL_select_next_proto function has been called as expected (with the list\nsupplied by the client passed in the client/client_len parameters), then the\napplication will not be vulnerable to this issue. If the application has\naccidentally been configured with a zero length server list, and has\naccidentally passed that zero length server list in the client/client_len\nparameters, and has additionally failed to correctly handle a \"no overlap\"\nresponse (which would normally result in a handshake failure in ALPN) then it\nwill be vulnerable to this problem.\n\nIn the case of NPN, the protocol permits the client to opportunistically select\na protocol when there is no overlap. OpenSSL returns the first client protocol\nin the no overlap case in support of this. The list of client protocols comes\nfrom the application and should never normally be expected to be of zero length.\nHowever if the SSL_select_next_proto function is accidentally called with a\nclient_len of 0 then an invalid memory pointer will be returned instead. If the\napplication uses this output as the opportunistic protocol then the loss of\nconfidentiality will occur.\n\nThis issue has been assessed as Low severity because applications are most\nlikely to be vulnerable if they are using NPN instead of ALPN - but NPN is not\nwidely used. It also requires an application configuration or programming error.\nFinally, this issue would not typically be under attacker control making active\nexploitation unlikely.\n\nThe FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.\n\nDue to the low severity of this issue we are not issuing new releases of\nOpenSSL at this time. The fix will be included in the next releases when they\nbecome available.",
                "cvss": [
                  {
                    "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "type": "Secondary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
                    "metrics": {
                      "baseScore": 9.1,
                      "exploitabilityScore": 3.9,
                      "impactScore": 5.2
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "rpm-matcher",
                "searchedBy": {
                  "distro": {
                    "type": "amazonlinux",
                    "version": "2"
                  },
                  "namespace": "amazon:distro:amazonlinux:2",
                  "package": {
                    "name": "openssl-libs",
                    "version": "1:1.0.2k-24.amzn2.0.12"
                  }
                },
                "found": {
                  "versionConstraint": "< 1.0.2k-24.amzn2.0.13 (rpm)",
                  "vulnerabilityID": "ALAS-2024-2604"
                }
              },
              {
                "type": "exact-indirect-match",
                "matcher": "rpm-matcher",
                "searchedBy": {
                  "distro": {
                    "type": "amazonlinux",
                    "version": "2"
                  },
                  "namespace": "amazon:distro:amazonlinux:2",
                  "package": {
                    "name": "openssl",
                    "version": "1.0.2k-24.amzn2.0.12"
                  }
                },
                "found": {
                  "versionConstraint": "< 1.0.2k-24.amzn2.0.13 (rpm)",
                  "vulnerabilityID": "ALAS-2024-2604"
                }
              }
            ],
            "artifact": {
              "id": "ca07aa6bdda5c274",
              "name": "openssl-libs",
              "version": "1:1.0.2k-24.amzn2.0.12",
              "type": "rpm",
              "locations": [
                {
                  "path": "/var/lib/rpm/Packages",
                  "layerID": "sha256:0044b36762beca646f20eb6730e3575ec671a8857b39485f38ba0e715d375483"
                }
              ],
              "language": "",
              "licenses": [
                "OpenSSL"
              ],
              "cpes": [
                "cpe:2.3:a:openssl-libs:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:openssl-libs:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:openssl_libs:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:openssl_libs:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:amazonlinux:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:amazonlinux:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:openssl:openssl-libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*",
                "cpe:2.3:a:openssl:openssl_libs:1:1.0.2k-24.amzn2.0.12:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:rpm/amzn/openssl-libs@1.0.2k-24.amzn2.0.12?arch=aarch64&epoch=1&upstream=openssl-1.0.2k-24.amzn2.0.12.src.rpm&distro=amzn-2",
              "upstreams": [
                {
                  "name": "openssl",
                  "version": "1.0.2k-24.amzn2.0.12"
                }
              ],
              "metadataType": "RpmMetadata",
              "metadata": {
                "epoch": 1,
                "modularityLabel": ""
              }
            }
          },
          {
            "vulnerability": {
              "id": "GHSA-mq26-g339-26xf",
              "dataSource": "https://github.com/advisories/GHSA-mq26-g339-26xf",
              "namespace": "github:language:python",
              "severity": "Medium",
              "urls": [
                "https://github.com/advisories/GHSA-mq26-g339-26xf"
              ],
              "description": "Command Injection in pip when used with Mercurial",
              "cvss": [
                {
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                  "metrics": {
                    "baseScore": 5.5,
                    "exploitabilityScore": 1.8,
                    "impactScore": 3.6
                  },
                  "vendorMetadata": {
                    "base_severity": "Medium",
                    "status": "N/A"
                  }
                }
              ],
              "fix": {
                "versions": [
                  "23.3"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2023-5752",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-5752",
                "namespace": "nvd:cpe",
                "severity": "Low",
                "urls": [
                  "https://github.com/pypa/pip/pull/12306",
                  "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/",
                  "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/",
                  "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/",
                  "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/",
                  "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/",
                  "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"
                ],
                "description": "When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.\n",
                "cvss": [
                  {
                    "source": "nvd@nist.gov",
                    "type": "Primary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
                    "metrics": {
                      "baseScore": 3.3,
                      "exploitabilityScore": 1.8,
                      "impactScore": 1.4
                    },
                    "vendorMetadata": {}
                  },
                  {
                    "source": "cna@python.org",
                    "type": "Secondary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                    "metrics": {
                      "baseScore": 5.5,
                      "exploitabilityScore": 1.8,
                      "impactScore": 3.6
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "python-matcher",
                "searchedBy": {
                  "language": "python",
                  "namespace": "github:language:python",
                  "package": {
                    "name": "pip",
                    "version": "23.0.1"
                  }
                },
                "found": {
                  "versionConstraint": "<23.3 (python)",
                  "vulnerabilityID": "GHSA-mq26-g339-26xf"
                }
              }
            ],
            "artifact": {
              "id": "8cac57bcd656efc6",
              "name": "pip",
              "version": "23.0.1",
              "type": "python",
              "locations": [
                {
                  "path": "/var/lang/lib/python3.9/site-packages/pip-23.0.1.dist-info/METADATA",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/python3.9/site-packages/pip-23.0.1.dist-info/RECORD",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/python3.9/site-packages/pip-23.0.1.dist-info/top_level.txt",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "python",
              "licenses": [
                "MIT"
              ],
              "cpes": [
                "cpe:2.3:a:pip_developers_project:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developers_project:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sig_project:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sig_project:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developersproject:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developersproject:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sigproject:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sigproject:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developers_project:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sig_project:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developers:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developers:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developersproject:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils-sig:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils-sig:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sig:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sig:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sigproject:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python-pip:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python-pip:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python_pip:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python_pip:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip_developers:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils-sig:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:distutils_sig:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pypa:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pypa:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip:python-pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip:python_pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python-pip:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python_pip:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pypa:pip:23.0.1:*:*:*:*:*:*:*",
                "cpe:2.3:a:pip:pip:23.0.1:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:pypi/pip@23.0.1",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-7592",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-7592",
              "namespace": "nvd:cpe",
              "severity": "High",
              "urls": [
                "https://github.com/python/cpython/issues/123067",
                "https://github.com/python/cpython/pull/123075",
                "https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/"
              ],
              "description": "There is a LOW severity vulnerability affecting CPython, specifically the\n'http.cookies' standard library module.\n\n\nWhen parsing cookies that contained backslashes for quoted characters in\nthe cookie value, the parser would use an algorithm with quadratic\ncomplexity, resulting in excess CPU resources being used while parsing the\nvalue.",
              "cvss": [
                {
                  "source": "nvd@nist.gov",
                  "type": "Primary",
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                  "metrics": {
                    "baseScore": 7.5,
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                  },
                  "vendorMetadata": {}
                }
              ],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-7592",
                  "versionConstraint": "<= 3.13.0 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-0397",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-0397",
              "namespace": "nvd:cpe",
              "severity": "High",
              "urls": [
                "http://www.openwall.com/lists/oss-security/2024/06/17/2",
                "https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d",
                "https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524",
                "https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e",
                "https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286",
                "https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa",
                "https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab",
                "https://github.com/python/cpython/issues/114572",
                "https://github.com/python/cpython/pull/114573",
                "https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/"
              ],
              "description": "A defect was discovered in the Python “ssl” module where there is a memory\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\n“get_ca_certs()”. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
              "cvss": [
                {
                  "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                  "type": "Secondary",
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
                  "metrics": {
                    "baseScore": 7.4,
                    "exploitabilityScore": 2.2,
                    "impactScore": 5.2
                  },
                  "vendorMetadata": {}
                }
              ],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-0397",
                  "versionConstraint": ">= 3.13.0a1, < 3.13.0a5 || >= 3.12.0, < 3.12.3 || >= 3.11.0, < 3.11.9 || < 3.10.14 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2023-36632",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-36632",
              "namespace": "nvd:cpe",
              "severity": "High",
              "urls": [
                "https://docs.python.org/3/library/email.html",
                "https://docs.python.org/3/library/email.utils.html",
                "https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py",
                "https://github.com/python/cpython/issues/103800"
              ],
              "description": "The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.",
              "cvss": [
                {
                  "source": "nvd@nist.gov",
                  "type": "Primary",
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                  "metrics": {
                    "baseScore": 7.5,
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                  },
                  "vendorMetadata": {}
                }
              ],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2023-36632",
                  "versionConstraint": "<= 3.11.4 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-6923",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-6923",
              "namespace": "nvd:cpe",
              "severity": "Medium",
              "urls": [
                "https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7",
                "https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0",
                "https://github.com/python/cpython/issues/121650",
                "https://github.com/python/cpython/pull/122233",
                "https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/"
              ],
              "description": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.",
              "cvss": [
                {
                  "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                  "type": "Secondary",
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L",
                  "metrics": {
                    "baseScore": 5.5,
                    "exploitabilityScore": 2.1,
                    "impactScore": 3.4
                  },
                  "vendorMetadata": {}
                }
              ],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-6923",
                  "versionConstraint": ">= 3.13.0a1, <= 3.13.0rc2 || < 3.12.5 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2023-27043",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-27043",
              "namespace": "nvd:cpe",
              "severity": "Medium",
              "urls": [
                "http://python.org",
                "https://github.com/python/cpython/issues/102988",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/",
                "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/",
                "https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html",
                "https://security.netapp.com/advisory/ntap-20230601-0003/"
              ],
              "description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
              "cvss": [
                {
                  "source": "nvd@nist.gov",
                  "type": "Primary",
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
                  "metrics": {
                    "baseScore": 5.3,
                    "exploitabilityScore": 3.9,
                    "impactScore": 1.4
                  },
                  "vendorMetadata": {}
                }
              ],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2023-27043",
                  "versionConstraint": "<= 2.7.18 || >= 3.0, <= 3.11 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-8088",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-8088",
              "namespace": "nvd:cpe",
              "severity": "Unknown",
              "urls": [
                "https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e",
                "https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64",
                "https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea",
                "https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db",
                "https://github.com/python/cpython/issues/122905",
                "https://github.com/python/cpython/issues/123270",
                "https://github.com/python/cpython/pull/122906",
                "https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/"
              ],
              "description": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.",
              "cvss": [],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-8088",
                  "versionConstraint": "<= 3.13.0 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-5642",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-5642",
              "namespace": "nvd:cpe",
              "severity": "Unknown",
              "urls": [
                "http://www.openwall.com/lists/oss-security/2024/06/28/4",
                "https://github.com/python/cpython/commit/39258d3595300bc7b952854c915f63ae2d4b9c3e",
                "https://github.com/python/cpython/issues/121227",
                "https://github.com/python/cpython/pull/23014",
                "https://jbp.io/2024/06/27/cve-2024-5535-openssl-memory-safety.html",
                "https://mail.python.org/archives/list/security-announce@python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/",
                "https://security.netapp.com/advisory/ntap-20240726-0005/"
              ],
              "description": "CPython 3.9 and earlier doesn't disallow configuring an empty list (\"[]\") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).",
              "cvss": [],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-5642",
                  "versionConstraint": "< 3.10.0b1 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-4032",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-4032",
              "namespace": "nvd:cpe",
              "severity": "Unknown",
              "urls": [
                "http://www.openwall.com/lists/oss-security/2024/06/17/3",
                "https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8",
                "https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f",
                "https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3",
                "https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb",
                "https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906",
                "https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3",
                "https://github.com/python/cpython/issues/113171",
                "https://github.com/python/cpython/pull/113179",
                "https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/",
                "https://security.netapp.com/advisory/ntap-20240726-0004/",
                "https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml",
                "https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"
              ],
              "description": "The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.",
              "cvss": [],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "stock-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "python",
                    "version": "3.9.19"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-4032",
                  "versionConstraint": "< 3.12.4 || >= 3.13.0a1, < 3.13.0a6 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "a120648b38c61b3b",
              "name": "python",
              "version": "3.9.19",
              "type": "binary",
              "locations": [
                {
                  "path": "/var/lang/bin/python3.9",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/libpython3.9.so.1.0",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "",
              "licenses": [],
              "cpes": [
                "cpe:2.3:a:python_software_foundation:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*",
                "cpe:2.3:a:python:python:3.9.19:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:generic/python@3.9.19",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "GHSA-r9hx-vwmv-q579",
              "dataSource": "https://github.com/advisories/GHSA-r9hx-vwmv-q579",
              "namespace": "github:language:python",
              "severity": "High",
              "urls": [
                "https://github.com/advisories/GHSA-r9hx-vwmv-q579"
              ],
              "description": "pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)",
              "cvss": [
                {
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                  "metrics": {
                    "baseScore": 7.5,
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                  },
                  "vendorMetadata": {
                    "base_severity": "High",
                    "status": "N/A"
                  }
                }
              ],
              "fix": {
                "versions": [
                  "65.5.1"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2022-40897",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
                "namespace": "nvd:cpe",
                "severity": "Medium",
                "urls": [
                  "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
                  "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
                  "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
                  "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
                  "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
                  "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
                  "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
                  "https://security.netapp.com/advisory/ntap-20230214-0001/",
                  "https://security.netapp.com/advisory/ntap-20240621-0006/"
                ],
                "description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
                "cvss": [
                  {
                    "source": "nvd@nist.gov",
                    "type": "Primary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "metrics": {
                      "baseScore": 5.9,
                      "exploitabilityScore": 2.2,
                      "impactScore": 3.6
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "python-matcher",
                "searchedBy": {
                  "language": "python",
                  "namespace": "github:language:python",
                  "package": {
                    "name": "setuptools",
                    "version": "58.1.0"
                  }
                },
                "found": {
                  "versionConstraint": "<65.5.1 (python)",
                  "vulnerabilityID": "GHSA-r9hx-vwmv-q579"
                }
              }
            ],
            "artifact": {
              "id": "bc6c39be42a59eb7",
              "name": "setuptools",
              "version": "58.1.0",
              "type": "python",
              "locations": [
                {
                  "path": "/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/METADATA",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/RECORD",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/top_level.txt",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "python",
              "licenses": [
                "UNKNOWN"
              ],
              "cpes": [
                "cpe:2.3:a:python:setuptools:58.1.0:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:pypi/setuptools@58.1.0",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "GHSA-cx63-2mw6-8hw5",
              "dataSource": "https://github.com/advisories/GHSA-cx63-2mw6-8hw5",
              "namespace": "github:language:python",
              "severity": "High",
              "urls": [
                "https://github.com/advisories/GHSA-cx63-2mw6-8hw5"
              ],
              "description": "setuptools vulnerable to Command Injection via package URL",
              "cvss": [
                {
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                  "metrics": {
                    "baseScore": 8.8,
                    "exploitabilityScore": 2.8,
                    "impactScore": 5.9
                  },
                  "vendorMetadata": {
                    "base_severity": "High",
                    "status": "N/A"
                  }
                }
              ],
              "fix": {
                "versions": [
                  "70.0.0"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2024-6345",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
                "namespace": "nvd:cpe",
                "severity": "High",
                "urls": [
                  "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0",
                  "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
                ],
                "description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
                "cvss": [
                  {
                    "source": "security@huntr.dev",
                    "type": "Secondary",
                    "version": "3.0",
                    "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "metrics": {
                      "baseScore": 8.8,
                      "exploitabilityScore": 2.8,
                      "impactScore": 5.9
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "python-matcher",
                "searchedBy": {
                  "language": "python",
                  "namespace": "github:language:python",
                  "package": {
                    "name": "setuptools",
                    "version": "58.1.0"
                  }
                },
                "found": {
                  "versionConstraint": "<70.0.0 (python)",
                  "vulnerabilityID": "GHSA-cx63-2mw6-8hw5"
                }
              }
            ],
            "artifact": {
              "id": "bc6c39be42a59eb7",
              "name": "setuptools",
              "version": "58.1.0",
              "type": "python",
              "locations": [
                {
                  "path": "/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/METADATA",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/RECORD",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                },
                {
                  "path": "/var/lang/lib/python3.9/site-packages/setuptools-58.1.0.dist-info/top_level.txt",
                  "layerID": "sha256:b98baf0908da50e172bd5dedbd8738e0ce574fe1d7229fec407c64e8725685c0"
                }
              ],
              "language": "python",
              "licenses": [
                "UNKNOWN"
              ],
              "cpes": [
                "cpe:2.3:a:python:setuptools:58.1.0:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:pypi/setuptools@58.1.0",
              "upstreams": []
            }
          },
          {
            "vulnerability": {
              "id": "CVE-2024-24791",
              "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-24791",
              "namespace": "nvd:cpe",
              "severity": "High",
              "urls": [
                "https://go.dev/cl/591255",
                "https://go.dev/issue/67555",
                "https://groups.google.com/g/golang-dev/c/t0rK-qHBqzY/m/6MMoAZkMAgAJ",
                "https://pkg.go.dev/vuln/GO-2024-2963"
              ],
              "description": "The net/http HTTP/1.1 client mishandled the case where a server responds to a request with an \"Expect: 100-continue\" header with a non-informational (200 or higher) status. This mishandling could leave a client connection in an invalid state, where the next request sent on the connection will fail. An attacker sending a request to a net/http/httputil.ReverseProxy proxy can exploit this mishandling to cause a denial of service by sending \"Expect: 100-continue\" requests which elicit a non-informational response from the backend. Each such request leaves the proxy with an invalid connection, and causes one subsequent request using that connection to fail.",
              "cvss": [
                {
                  "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                  "type": "Secondary",
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                  "metrics": {
                    "baseScore": 7.5,
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                  },
                  "vendorMetadata": {}
                }
              ],
              "fix": {
                "versions": [],
                "state": "unknown"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [],
            "matchDetails": [
              {
                "type": "cpe-match",
                "matcher": "go-module-matcher",
                "searchedBy": {
                  "namespace": "nvd:cpe",
                  "cpes": [
                    "cpe:2.3:a:golang:go:1.22.4:-:*:*:*:*:*:*"
                  ],
                  "package": {
                    "name": "stdlib",
                    "version": "go1.22.4"
                  }
                },
                "found": {
                  "vulnerabilityID": "CVE-2024-24791",
                  "versionConstraint": "< 1.21.12 || >= 1.22.0-0, < 1.22.5 (unknown)",
                  "cpes": [
                    "cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*"
                  ]
                }
              }
            ],
            "artifact": {
              "id": "c93538cbf3d8e93b",
              "name": "stdlib",
              "version": "go1.22.4",
              "type": "go-module",
              "locations": [
                {
                  "path": "/usr/local/bin/aws-lambda-rie",
                  "layerID": "sha256:9a9b5814afc2b76039ada8e0f4445eeec0c487bcf7637b36b20a7f25bb15b369"
                }
              ],
              "language": "go",
              "licenses": [
                "BSD-3-Clause"
              ],
              "cpes": [
                "cpe:2.3:a:golang:go:1.22.4:-:*:*:*:*:*:*"
              ],
              "purl": "pkg:golang/stdlib@1.22.4",
              "upstreams": [],
              "metadataType": "GolangBinMetadata",
              "metadata": {
                "goCompiledVersion": "go1.22.4",
                "architecture": ""
              }
            }
          },
          {
            "vulnerability": {
              "id": "GHSA-34jh-p97f-mpxf",
              "dataSource": "https://github.com/advisories/GHSA-34jh-p97f-mpxf",
              "namespace": "github:language:python",
              "severity": "Medium",
              "urls": [
                "https://github.com/advisories/GHSA-34jh-p97f-mpxf"
              ],
              "description": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects ",
              "cvss": [
                {
                  "version": "3.1",
                  "vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                  "metrics": {
                    "baseScore": 4.4,
                    "exploitabilityScore": 0.7,
                    "impactScore": 3.6
                  },
                  "vendorMetadata": {
                    "base_severity": "Medium",
                    "status": "N/A"
                  }
                }
              ],
              "fix": {
                "versions": [
                  "1.26.19"
                ],
                "state": "fixed"
              },
              "advisories": []
            },
            "relatedVulnerabilities": [
              {
                "id": "CVE-2024-37891",
                "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891",
                "namespace": "nvd:cpe",
                "severity": "Medium",
                "urls": [
                  "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e",
                  "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
                ],
                "description": " urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.",
                "cvss": [
                  {
                    "source": "security-advisories@github.com",
                    "type": "Secondary",
                    "version": "3.1",
                    "vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                    "metrics": {
                      "baseScore": 4.4,
                      "exploitabilityScore": 0.7,
                      "impactScore": 3.6
                    },
                    "vendorMetadata": {}
                  }
                ]
              }
            ],
            "matchDetails": [
              {
                "type": "exact-direct-match",
                "matcher": "python-matcher",
                "searchedBy": {
                  "language": "python",
                  "namespace": "github:language:python",
                  "package": {
                    "name": "urllib3",
                    "version": "1.26.18"
                  }
                },
                "found": {
                  "versionConstraint": "<1.26.19 (python)",
                  "vulnerabilityID": "GHSA-34jh-p97f-mpxf"
                }
              }
            ],
            "artifact": {
              "id": "18a6c87286e142af",
              "name": "urllib3",
              "version": "1.26.18",
              "type": "python",
              "locations": [
                {
                  "path": "/var/runtime/urllib3-1.26.18.dist-info/METADATA",
                  "layerID": "sha256:734a487fcc033d64cea626bc74e5937eda7014ad9b80d4b3af36f5cce52d2b03"
                },
                {
                  "path": "/var/runtime/urllib3-1.26.18.dist-info/RECORD",
                  "layerID": "sha256:734a487fcc033d64cea626bc74e5937eda7014ad9b80d4b3af36f5cce52d2b03"
                },
                {
                  "path": "/var/runtime/urllib3-1.26.18.dist-info/top_level.txt",
                  "layerID": "sha256:734a487fcc033d64cea626bc74e5937eda7014ad9b80d4b3af36f5cce52d2b03"
                }
              ],
              "language": "python",
              "licenses": [
                "MIT"
              ],
              "cpes": [
                "cpe:2.3:a:python:urllib3:1.26.18:*:*:*:*:*:*:*"
              ],
              "purl": "pkg:pypi/urllib3@1.26.18",
              "upstreams": []
            }
          }
        ]
      }
    }
  }
}